### ISSUE TITLE
Inquiry about Evaluation Metrics for ScenePrior Project

### ISSUE THREAD

**Issue by kangx326** [yinyunie/ScenePriors#10]
Hi, Yinyu, as I am exploring your project, I am particularly interested in understanding how the evaluation metrics are computed. I believe that a clear grasp of the metrics will help me better evaluate the performance of the models and compare it with other similar works.

Could you please provide me with some details on the following:
Are there any specific scripts or tools within the repository that are dedicated to calculating these metrics?
If possible, could you also share any references to the standards or methods that these metrics are based upon?

Thank you for your time and assistance. I look forward to your response.

Best regards,
Xin

**Comment by yinyunie** [comment]
Hi Xin,

I followed ATISS to do the evaluation. Please check the scripts here: https://github.com/nv-tlabs/ATISS/tree/master/scripts
