### ISSUE TITLE
Inquire about 3D-FRONT preprocessing(rendering with BlenderProc2)

### ISSUE THREAD

**Issue by JJukE** [yinyunie/ScenePriors#3]
Hello,

Thank you for providing this codes of the awesome work!

I'm wondering if the rendering process and the result are right.

In my case, I commented out only 'bproc.renderer.enable_depth_output(activate_antialiasing=False)' line, not commented out the 'bproc.renderer.enable_normals_output()' line in 'render_dataset_improved_mat.py' file.
Also, I run this shellscript:

CUDA_VISIBLE_DEVICES=0,1 \
python ./examples/datasets/front_3d_with_improved_mat/multi_render.py \
./examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py \
./examples/datasets/front_3d_with_improved_mat/3D-FRONT \
./examples/datasets/front_3d_with_improved_mat/3D-FUTURE-model \
./examples/datasets/front_3d_with_improved_mat/3D-FRONT-texture \
--blender_path /root/dev/blender \
--cc_material_folder ./resources/cctextures/ \
--output_folder /root/hdd1/ScenePriors/3D-FRONT_renderings_normal/3D-FRONT_renderings_improved_mat \
--n_processes 2

And the results are as below:
in the result folder...
- 6,190 folders of rendered scene containing 101 hdf5 files
- failed_scene_names.txt containing 623 lines of scenes failed to render

As far as I understood, **the number of sum of rendered folders and failed scenes** (6,190 + 623) **should be same to the number of items in 3D-FUTURE-model folder** (16,565), but it's not.

Is there any wrong process to preprocess in my case? If not, why are the numbers different?

Thank you!

**Comment by yinyunie** [comment]
Hi,

6,190 + 623 should be equal to the number of scenes (apartments) in 3D-Front. 3D-FUTURE is a single-object dataset which contains all the CAD models shared in different scenes.

Best,
Yinyu

**Comment by JJukE** [comment]
Thank you for your response!
