### ISSUE TITLE
Question on number of objects

### ISSUE THREAD

**Issue by DianCh** [yinyunie/ScenePriors#7]
Hi! I have a few questions on the number of objects to render and train: it looks like the maximum number of objects for ScanNet is set to 7 - what if the scene contains less than 7 objects? How does the hungarian matching and batched mesh rendering work? On the contrary, when the scene contains more than 7 objects, does it mean the extra objects are simply ignored?

Thank you very much!

**Comment by yinyunie** [comment]
Hi,

If I remember, I set max_n_obj = 53. Could you please share with me where I set it to 7? Thanks.

Best,
Yinyu

**Comment by DianCh** [comment]
<img width="936" alt="Screen Shot 2023-08-30 at 9 45 39 AM" src="https://github.com/yinyunie/ScenePriors/assets/32043460/e704cf15-4ccd-4b77-8e0b-955e4e6b3943">

from `models/ours/modules/network.py`

Here for example `max_len` got the value of 7 in the batch during training (which isn't set fixed, I misunderstood), which I realized that won't result in extra objects being ignored; but how does it work for extra meshes - like when there are 7 meshes for the second sample with 5 objects?

Thanks!

**Comment by yinyunie** [comment]
Hi,

`max_len` is the maximum number of objects in a batch. For example, if there are two scenes in a batch - Scene A has 5 objects, and Scene B has 7 objects, `max_len` will be 7. I also loaded an object mask for each scene, so Scene A has a 7-d binary vector mask with the first 5 entries occupied, while the others are zeros.
